#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Paulo Jr'
        hostname: ubuntu
        username: paulojr
        password: '$6$qc8l/dqqH5Umignh$sAYz8bhT/E/I7yDpib4wkVBFLzK/j6KUzrB0nT9J.Z6z368chgC16Z10EVvG1iPobrD1ic6eMLdGL6cf1uVmz1'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    storage:
    layout:
      name: lvm
      sizing-policy: all
      password: ubuntu
    timezone: "America/Sao_Paulo"   
    packages:
        - sudo
        - git
        - wget
        - build-essential
        - curl
        - net-tools
        - git
        - vim
        - iptraf
        - btop
        - terminator
        - python3
        - python3-venv
        - ubuntucinnamon-desktop
        - ubuntucinnamon-wallpapers-noble
        - gpg
        - apt-transport-https
        - software-properties-common
        - ca-certificates
        - bluez
    late-commands:
        - curtin in-target -- sudo apt autoremove -y
    ssh:
      install-server: true
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
