#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Paulo Roberto Alves Resende Júnior'
        hostname: ubuntu
        username: paulojr
        password: '$6$6mym/qpkPW5Kui7f$fLKe6H2QVxr41Rm2rHzQKh4TGa8ecchvKN5wPVxzGoMtcAIwRW2dtS.dsJJYItuBFv28UluCTR72fuycMnBsd.'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - git
        - wget
        - build-essential
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
