#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Paulo Jr'
        hostname: ubuntu
        username: paulojr
        password: '$6$qc8l/dqqH5Umignh$sAYz8bhT/E/I7yDpib4wkVBFLzK/j6KUzrB0nT9J.Z6z368chgC16Z10EVvG1iPobrD1ic6eMLdGL6cf1uVmz1'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    storage:
    layout:
      name: lvm
      sizing-policy: all
      password: ubuntu
    timezone: "America/Sao_Paulo"   
    packages:
        - sudo
        - git
        - wget
        - build-essential
        - curl
        - net-tools
        - git
        - vim
        - iptraf
        - btop
        - terminator
        - python3
        - python3-venv
        - ubuntucinnamon-desktop
        - ubuntucinnamon-wallpapers-noble
        - gpg
        - apt-transport-https
        - software-properties-common
        - ca-certificates
        - bluez
    late-commands:
        # Venv Python        
        - curtin in-target -- python3 -m venv ubuntu
        # Edge ' Vscode'        
        - curtin in-target -- curl -fSsL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-edge.gpg > /dev/null
        - curtin in-target -- echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-edge.gpg] https://packages.microsoft.com/repos/edge stable main' | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
        - curtin in-target -- sudo apt update -y && sudo apt install -y microsoft-edge-stable code
        # Chrome
        - curtin in-target -- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - curtin in-target -- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        - curtin in-target -- sudo apt-get update -y && sudo apt-get install google-chrome-stable
    ssh:
      install-server: true
    # snaps:
    #     - name: spotify
    #       channel: stable
    #       classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
